Repository cybozu-go/cattage, pull requests merged in 2025-07, with the labels that each got.

#70 Update dependency aquaproj/aqua-registry to v4.384.0
  aqua.yaml
Labels: dependencies

#72 Fix renovate config warnings
  .github/workflows/renovate.yaml
  config.json
  renovate.json
  renovate.json5
Labels: ci

#80 Update dependency aquaproj/aqua to v2.53.6
  .github/actions/aqua/action.yaml
Labels: dependencies

#79 Add RBAC aggregation labels for sync window roles
  Makefile
  charts/cattage/Chart.yaml
  charts/cattage/crds/crds.yaml
  charts/cattage/templates/generated.yaml
  config/rbac/syncwindow_editor_role.yaml
  config/rbac/syncwindow_viewer_role.yaml
  config/rbac/tenant_editor_role.yaml
  config/rbac/tenant_viewer_role.yaml
Labels: bug

#84 Update dependency kubernetes-sigs/kustomize to v5.7.1
  aqua.yaml
Labels: dependencies

#83 Update dependency aquaproj/aqua to v2.53.7
  .github/actions/aqua/action.yaml
Labels: dependencies
